-- À exécuter dans Supabase > SQL Editor
-- Table des fêtes / prénoms du calendrier français (un jour = un ou plusieurs prénoms).
-- Source principale : Super Prénom (superprenom.fr) via data.gouv.fr — Licence Ouverte / CC BY.
-- Jours manquants complétés d'après le calendrier français usuel (Nominis / tradition civile).
-- Régénérer : node scripts/build-fete-sql.mjs

CREATE TABLE IF NOT EXISTS public.fete (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  day SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
  names TEXT[] NOT NULL CHECK (cardinality(names) >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS fete_unique_month_day
  ON public.fete (month, day);

CREATE INDEX IF NOT EXISTS fete_month_day_idx
  ON public.fete (month, day);

ALTER TABLE public.fete ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read fete" ON public.fete;
CREATE POLICY "Authenticated can read fete"
  ON public.fete
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Admins can manage fete" ON public.fete;
CREATE POLICY "Admins can manage fete"
  ON public.fete
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'super_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role IN ('admin', 'super_admin')
    )
  );

TRUNCATE public.fete;

INSERT INTO public.fete (month, day, names) VALUES
  (1, 1, ARRAY['Marie']::text[]),
  (1, 2, ARRAY['Basile']::text[]),
  (1, 3, ARRAY['Genevieve', 'Ginette']::text[]),
  (1, 4, ARRAY['Odilon']::text[]),
  (1, 5, ARRAY['Edouard']::text[]),
  (1, 6, ARRAY['Mélaine']::text[]),
  (1, 7, ARRAY['Cedric', 'Raymond', 'Raymonde', 'Virginie']::text[]),
  (1, 8, ARRAY['Lucien', 'Lucienne']::text[]),
  (1, 9, ARRAY['Alix']::text[]),
  (1, 10, ARRAY['Guillaume', 'Leonie', 'William']::text[]),
  (1, 11, ARRAY['Paulin']::text[]),
  (1, 12, ARRAY['Tatiana']::text[]),
  (1, 13, ARRAY['Yvette']::text[]),
  (1, 14, ARRAY['Nina']::text[]),
  (1, 15, ARRAY['Remi']::text[]),
  (1, 16, ARRAY['Marcel']::text[]),
  (1, 17, ARRAY['Roseline']::text[]),
  (1, 18, ARRAY['Prisca']::text[]),
  (1, 19, ARRAY['Marius']::text[]),
  (1, 20, ARRAY['Fabien', 'Sebastien']::text[]),
  (1, 21, ARRAY['Agnes']::text[]),
  (1, 22, ARRAY['Vincent']::text[]),
  (1, 23, ARRAY['Barnard']::text[]),
  (1, 24, ARRAY['François de Sales']::text[]),
  (1, 25, ARRAY['Paul']::text[]),
  (1, 26, ARRAY['Melanie', 'Timothe', 'Timothee']::text[]),
  (1, 27, ARRAY['Angèle']::text[]),
  (1, 28, ARRAY['Thomas d''Aquin']::text[]),
  (1, 29, ARRAY['Sabrina']::text[]),
  (1, 30, ARRAY['Martine']::text[]),
  (1, 31, ARRAY['Marcelle']::text[]),
  (2, 1, ARRAY['Ella']::text[]),
  (2, 2, ARRAY['Présentation']::text[]),
  (2, 3, ARRAY['Blaise']::text[]),
  (2, 4, ARRAY['Berenice', 'Gilbert', 'Vanessa', 'Veronique']::text[]),
  (2, 5, ARRAY['Agathe']::text[]),
  (2, 6, ARRAY['Gaston']::text[]),
  (2, 7, ARRAY['Eugénie']::text[]),
  (2, 8, ARRAY['Jacqueline']::text[]),
  (2, 9, ARRAY['Apolline']::text[]),
  (2, 10, ARRAY['Arnaud']::text[]),
  (2, 11, ARRAY['Heloise']::text[]),
  (2, 12, ARRAY['Felix']::text[]),
  (2, 13, ARRAY['Beatrice', 'Jordan']::text[]),
  (2, 14, ARRAY['Valentin', 'Valentine']::text[]),
  (2, 15, ARRAY['Claude', 'Claudine', 'Faustine', 'Georgette', 'Jean-claude', 'Marie-claude']::text[]),
  (2, 16, ARRAY['Julienne']::text[]),
  (2, 17, ARRAY['Alexis']::text[]),
  (2, 18, ARRAY['Bernadette']::text[]),
  (2, 19, ARRAY['Gabin']::text[]),
  (2, 20, ARRAY['Aimée']::text[]),
  (2, 21, ARRAY['Pierre-Damien']::text[]),
  (2, 22, ARRAY['Isabelle']::text[]),
  (2, 23, ARRAY['Isabelle']::text[]),
  (2, 24, ARRAY['Modeste']::text[]),
  (2, 25, ARRAY['Roméo']::text[]),
  (2, 26, ARRAY['Nestor']::text[]),
  (2, 27, ARRAY['Honorine']::text[]),
  (2, 28, ARRAY['Romain', 'Romane']::text[]),
  (2, 29, ARRAY['Auguste']::text[]),
  (3, 1, ARRAY['Jonathan']::text[]),
  (3, 2, ARRAY['Charles le Bon']::text[]),
  (3, 3, ARRAY['Camille']::text[]),
  (3, 4, ARRAY['Casimir']::text[]),
  (3, 5, ARRAY['Olivia']::text[]),
  (3, 6, ARRAY['Colette', 'Nicole']::text[]),
  (3, 7, ARRAY['Félicité']::text[]),
  (3, 8, ARRAY['Jean de Dieu']::text[]),
  (3, 9, ARRAY['Francine', 'Francoise', 'Marie-france', 'Marie-francoise']::text[]),
  (3, 10, ARRAY['Vivien']::text[]),
  (3, 11, ARRAY['Rosine']::text[]),
  (3, 12, ARRAY['Justine']::text[]),
  (3, 13, ARRAY['Patricia']::text[]),
  (3, 14, ARRAY['Maeva', 'Mathilde']::text[]),
  (3, 15, ARRAY['Lou', 'Louise', 'Marie-louise']::text[]),
  (3, 16, ARRAY['Bénédicte']::text[]),
  (3, 17, ARRAY['Patrick']::text[]),
  (3, 18, ARRAY['Cyril']::text[]),
  (3, 19, ARRAY['Joseph', 'Josephine', 'Josette', 'Josiane', 'Marie-jose']::text[]),
  (3, 20, ARRAY['Alexandra', 'Enzo']::text[]),
  (3, 21, ARRAY['Axel', 'Clemence']::text[]),
  (3, 22, ARRAY['Lea']::text[]),
  (3, 23, ARRAY['Rebecca']::text[]),
  (3, 24, ARRAY['Catherine de Suède']::text[]),
  (3, 25, ARRAY['Annonciation']::text[]),
  (3, 26, ARRAY['Paulette', 'Pauline']::text[]),
  (3, 27, ARRAY['Habib']::text[]),
  (3, 28, ARRAY['Gontran']::text[]),
  (3, 29, ARRAY['Gwladys']::text[]),
  (3, 30, ARRAY['Amédée']::text[]),
  (3, 31, ARRAY['Benjamin']::text[]),
  (4, 1, ARRAY['Hugo', 'Hugues', 'Huguette']::text[]),
  (4, 2, ARRAY['Sandrine', 'Ulysse']::text[]),
  (4, 3, ARRAY['Richard']::text[]),
  (4, 4, ARRAY['Isidore']::text[]),
  (4, 5, ARRAY['Irene']::text[]),
  (4, 6, ARRAY['Marcellin']::text[]),
  (4, 7, ARRAY['Jean-Baptiste de La Salle']::text[]),
  (4, 8, ARRAY['Constance', 'Julia', 'Julie']::text[]),
  (4, 9, ARRAY['Gautier']::text[]),
  (4, 10, ARRAY['Fulbert']::text[]),
  (4, 11, ARRAY['Stanislas']::text[]),
  (4, 12, ARRAY['Jules']::text[]),
  (4, 13, ARRAY['Ida']::text[]),
  (4, 14, ARRAY['Maxime']::text[]),
  (4, 15, ARRAY['Cesar']::text[]),
  (4, 16, ARRAY['Benoît-Joseph']::text[]),
  (4, 17, ARRAY['Anicet']::text[]),
  (4, 18, ARRAY['Parfait']::text[]),
  (4, 19, ARRAY['Emma', 'Luna']::text[]),
  (4, 20, ARRAY['Odette']::text[]),
  (4, 21, ARRAY['Anselme']::text[]),
  (4, 22, ARRAY['Alexandre']::text[]),
  (4, 23, ARRAY['Georges']::text[]),
  (4, 24, ARRAY['Fidèle']::text[]),
  (4, 25, ARRAY['Jean-marc', 'Marc']::text[]),
  (4, 26, ARRAY['Alida']::text[]),
  (4, 27, ARRAY['Zita']::text[]),
  (4, 28, ARRAY['Valerie']::text[]),
  (4, 29, ARRAY['Catherine de Sienne']::text[]),
  (4, 30, ARRAY['Robert', 'Robin']::text[]),
  (5, 1, ARRAY['Brieuc']::text[]),
  (5, 2, ARRAY['Zoe']::text[]),
  (5, 3, ARRAY['Jean-philippe', 'Philippe']::text[]),
  (5, 4, ARRAY['Florian']::text[]),
  (5, 5, ARRAY['Penelope']::text[]),
  (5, 6, ARRAY['Prudence']::text[]),
  (5, 7, ARRAY['Gisèle']::text[]),
  (5, 8, ARRAY['Désiré']::text[]),
  (5, 9, ARRAY['Pacôme']::text[]),
  (5, 10, ARRAY['Solange']::text[]),
  (5, 11, ARRAY['Estelle']::text[]),
  (5, 12, ARRAY['Achille']::text[]),
  (5, 13, ARRAY['Mael']::text[]),
  (5, 14, ARRAY['Matthias']::text[]),
  (5, 15, ARRAY['Denise']::text[]),
  (5, 16, ARRAY['Honoré']::text[]),
  (5, 17, ARRAY['Pascal', 'Pascale']::text[]),
  (5, 18, ARRAY['Corinne', 'Eric']::text[]),
  (5, 19, ARRAY['Erwan', 'Jean-yves', 'Yves', 'Yvonne']::text[]),
  (5, 20, ARRAY['Bernardin']::text[]),
  (5, 21, ARRAY['Constantin']::text[]),
  (5, 22, ARRAY['Emile']::text[]),
  (5, 23, ARRAY['Didier']::text[]),
  (5, 24, ARRAY['Donatien']::text[]),
  (5, 25, ARRAY['Anne-sophie', 'Sonia', 'Sophie']::text[]),
  (5, 26, ARRAY['Eden']::text[]),
  (5, 27, ARRAY['Augustin']::text[]),
  (5, 28, ARRAY['Germain']::text[]),
  (5, 29, ARRAY['Aymar']::text[]),
  (5, 30, ARRAY['Jeanne', 'Jeannine']::text[]),
  (5, 31, ARRAY['Pierrette']::text[]),
  (6, 1, ARRAY['Ronan']::text[]),
  (6, 2, ARRAY['Blandine']::text[]),
  (6, 3, ARRAY['Kevin']::text[]),
  (6, 4, ARRAY['Clotilde']::text[]),
  (6, 5, ARRAY['Igor']::text[]),
  (6, 6, ARRAY['Norbert']::text[]),
  (6, 7, ARRAY['Gilbert']::text[]),
  (6, 8, ARRAY['Médard']::text[]),
  (6, 9, ARRAY['Diane']::text[]),
  (6, 10, ARRAY['Landry']::text[]),
  (6, 11, ARRAY['Barnabé']::text[]),
  (6, 12, ARRAY['Guy']::text[]),
  (6, 13, ARRAY['Anthony', 'Antoine']::text[]),
  (6, 14, ARRAY['Élisée']::text[]),
  (6, 15, ARRAY['Germaine']::text[]),
  (6, 16, ARRAY['Régis']::text[]),
  (6, 17, ARRAY['Adam', 'Alba', 'Herve']::text[]),
  (6, 18, ARRAY['Léonce']::text[]),
  (6, 19, ARRAY['Romuald']::text[]),
  (6, 20, ARRAY['Silvère']::text[]),
  (6, 21, ARRAY['Rodolphe']::text[]),
  (6, 22, ARRAY['Aaron', 'Alban']::text[]),
  (6, 23, ARRAY['Audrey']::text[]),
  (6, 24, ARRAY['Baptiste', 'Jean', 'Jean-baptiste', 'Yann', 'Yannick']::text[]),
  (6, 25, ARRAY['Eleonore', 'Prosper']::text[]),
  (6, 26, ARRAY['Anthelme']::text[]),
  (6, 27, ARRAY['Fernand']::text[]),
  (6, 28, ARRAY['Irénée']::text[]),
  (6, 29, ARRAY['Jade', 'Jean-paul', 'Jean-pierre', 'Marie-pierre', 'Paul', 'Pierre']::text[]),
  (6, 30, ARRAY['Martial']::text[]),
  (7, 1, ARRAY['Alienor', 'Thierry']::text[]),
  (7, 2, ARRAY['Martinien']::text[]),
  (7, 3, ARRAY['Thomas', 'Tom']::text[]),
  (7, 4, ARRAY['Florent']::text[]),
  (7, 5, ARRAY['Sacha']::text[]),
  (7, 6, ARRAY['Nolwenn']::text[]),
  (7, 7, ARRAY['Raoul']::text[]),
  (7, 8, ARRAY['Thibaut']::text[]),
  (7, 9, ARRAY['Amandine']::text[]),
  (7, 10, ARRAY['Ulric']::text[]),
  (7, 11, ARRAY['Benoit']::text[]),
  (7, 12, ARRAY['Olivier']::text[]),
  (7, 13, ARRAY['Chloe', 'Eugene', 'Henri', 'Henriette', 'Joëlle']::text[]),
  (7, 14, ARRAY['Camille de Lellis']::text[]),
  (7, 15, ARRAY['Donald']::text[]),
  (7, 16, ARRAY['Carmen']::text[]),
  (7, 17, ARRAY['Caroline', 'Charlotte']::text[]),
  (7, 18, ARRAY['Frederic']::text[]),
  (7, 19, ARRAY['Arsène']::text[]),
  (7, 20, ARRAY['Marine']::text[]),
  (7, 21, ARRAY['Victor']::text[]),
  (7, 22, ARRAY['Madeleine']::text[]),
  (7, 23, ARRAY['Brigitte']::text[]),
  (7, 24, ARRAY['Christelle', 'Christine', 'Marie-christine']::text[]),
  (7, 25, ARRAY['Christophe', 'Jacques', 'Jean-christophe', 'Jean-jacques']::text[]),
  (7, 26, ARRAY['Anais', 'Anna', 'Anne', 'Anne-marie', 'Annie']::text[]),
  (7, 27, ARRAY['Liliane', 'Nathalie']::text[]),
  (7, 28, ARRAY['Samson']::text[]),
  (7, 29, ARRAY['Marthe']::text[]),
  (7, 30, ARRAY['Juliette']::text[]),
  (7, 31, ARRAY['Ignace de Loyola']::text[]),
  (8, 1, ARRAY['Alphonse']::text[]),
  (8, 2, ARRAY['Julien']::text[]),
  (8, 3, ARRAY['Lydie']::text[]),
  (8, 4, ARRAY['Jean-Marie Vianney']::text[]),
  (8, 5, ARRAY['Abel']::text[]),
  (8, 6, ARRAY['Transfiguration']::text[]),
  (8, 7, ARRAY['Gaétan']::text[]),
  (8, 8, ARRAY['Dominique']::text[]),
  (8, 9, ARRAY['Amour']::text[]),
  (8, 10, ARRAY['Laure', 'Laurence', 'Laurent', 'Marie-laure']::text[]),
  (8, 11, ARRAY['Clara', 'Marie-claire', 'Suzanne']::text[]),
  (8, 12, ARRAY['Clarisse']::text[]),
  (8, 13, ARRAY['Hippolyte']::text[]),
  (8, 14, ARRAY['Évrard']::text[]),
  (8, 15, ARRAY['Alfred', 'Jean-marie', 'Manon', 'Marie', 'Marion', 'Maryse', 'Mireille', 'Myriam']::text[]),
  (8, 16, ARRAY['Armel']::text[]),
  (8, 17, ARRAY['Hyacinthe']::text[]),
  (8, 18, ARRAY['Elena', 'Helene', 'Laetitia', 'Marie-helene']::text[]),
  (8, 19, ARRAY['Ethan', 'Michele']::text[]),
  (8, 20, ARRAY['Bernard', 'Samuel']::text[]),
  (8, 21, ARRAY['Noemie']::text[]),
  (8, 22, ARRAY['Fabrice']::text[]),
  (8, 23, ARRAY['Rose']::text[]),
  (8, 24, ARRAY['Nathan']::text[]),
  (8, 25, ARRAY['Jean-louis', 'Loic', 'Louis', 'Ludovic']::text[]),
  (8, 26, ARRAY['Natacha']::text[]),
  (8, 27, ARRAY['Monique']::text[]),
  (8, 28, ARRAY['Auguste', 'Augustin']::text[]),
  (8, 29, ARRAY['Sabine']::text[]),
  (8, 30, ARRAY['Fiacre']::text[]),
  (8, 31, ARRAY['Aristide']::text[]),
  (9, 1, ARRAY['Gilles']::text[]),
  (9, 2, ARRAY['Ingrid']::text[]),
  (9, 3, ARRAY['Dylan', 'Gregory']::text[]),
  (9, 4, ARRAY['Iris']::text[]),
  (9, 5, ARRAY['Raïssa']::text[]),
  (9, 6, ARRAY['Eva']::text[]),
  (9, 7, ARRAY['Roxane']::text[]),
  (9, 8, ARRAY['Adrien']::text[]),
  (9, 9, ARRAY['Alain']::text[]),
  (9, 10, ARRAY['Ines']::text[]),
  (9, 11, ARRAY['Jeremy']::text[]),
  (9, 12, ARRAY['Apollinaire']::text[]),
  (9, 13, ARRAY['Aimé']::text[]),
  (9, 14, ARRAY['Croix Glorieuse']::text[]),
  (9, 15, ARRAY['Lola', 'Roland']::text[]),
  (9, 16, ARRAY['Mila']::text[]),
  (9, 17, ARRAY['Renaud']::text[]),
  (9, 18, ARRAY['Nadine', 'Oceane']::text[]),
  (9, 19, ARRAY['Amelie', 'Emilie']::text[]),
  (9, 20, ARRAY['Davy']::text[]),
  (9, 21, ARRAY['Mathieu', 'Mathis', 'Matteo', 'Matthieu']::text[]),
  (9, 22, ARRAY['Maurice']::text[]),
  (9, 23, ARRAY['Lina']::text[]),
  (9, 24, ARRAY['Thècle']::text[]),
  (9, 25, ARRAY['Hermann']::text[]),
  (9, 26, ARRAY['Damien']::text[]),
  (9, 27, ARRAY['Vincent de Paul']::text[]),
  (9, 28, ARRAY['Venceslas']::text[]),
  (9, 29, ARRAY['Gabriel', 'Gabrielle', 'Jean-michel', 'Michel', 'Michèle', 'Micheline', 'Raphael']::text[]),
  (9, 30, ARRAY['Jerome']::text[]),
  (10, 1, ARRAY['Marie-therese', 'Theo', 'Therese']::text[]),
  (10, 2, ARRAY['Léger']::text[]),
  (10, 3, ARRAY['Blanche', 'Gerard']::text[]),
  (10, 4, ARRAY['Francis', 'Franck', 'Francois', 'Jean-francois']::text[]),
  (10, 5, ARRAY['Capucine', 'Yasmine']::text[]),
  (10, 6, ARRAY['Bruno']::text[]),
  (10, 7, ARRAY['Gustave', 'Serge']::text[]),
  (10, 8, ARRAY['Pélagie']::text[]),
  (10, 9, ARRAY['Denis', 'Sarah']::text[]),
  (10, 10, ARRAY['Ghislain']::text[]),
  (10, 11, ARRAY['Firmin']::text[]),
  (10, 12, ARRAY['Wilfried']::text[]),
  (10, 13, ARRAY['Géraud']::text[]),
  (10, 14, ARRAY['Celeste', 'Enora']::text[]),
  (10, 15, ARRAY['Aurelie']::text[]),
  (10, 16, ARRAY['Edwige']::text[]),
  (10, 17, ARRAY['Garance']::text[]),
  (10, 18, ARRAY['Jean-luc', 'Lucas']::text[]),
  (10, 19, ARRAY['Gabin', 'Laura', 'Lena', 'Rene', 'Renee']::text[]),
  (10, 20, ARRAY['Aline']::text[]),
  (10, 21, ARRAY['Celine']::text[]),
  (10, 22, ARRAY['Elodie', 'Morgan', 'Salome']::text[]),
  (10, 23, ARRAY['Romy']::text[]),
  (10, 24, ARRAY['Florentin']::text[]),
  (10, 25, ARRAY['Alma']::text[]),
  (10, 26, ARRAY['Dimitri']::text[]),
  (10, 27, ARRAY['Émeline']::text[]),
  (10, 28, ARRAY['Simon', 'Simone', 'Simonne']::text[]),
  (10, 29, ARRAY['Narcisse']::text[]),
  (10, 30, ARRAY['Bienvenue']::text[]),
  (10, 31, ARRAY['Quentin']::text[]),
  (11, 1, ARRAY['Toussaint']::text[]),
  (11, 2, ARRAY['Défunts']::text[]),
  (11, 3, ARRAY['Gwenaëlle', 'Liam']::text[]),
  (11, 4, ARRAY['Charles', 'Jean-charles']::text[]),
  (11, 5, ARRAY['Sylvie']::text[]),
  (11, 6, ARRAY['Leonard']::text[]),
  (11, 7, ARRAY['Ernest', 'Karine']::text[]),
  (11, 8, ARRAY['Geoffroy']::text[]),
  (11, 9, ARRAY['Théodore']::text[]),
  (11, 10, ARRAY['Leo', 'Leon', 'Lionel', 'Noah']::text[]),
  (11, 11, ARRAY['Martin']::text[]),
  (11, 12, ARRAY['Christian', 'Emilien', 'Tristan']::text[]),
  (11, 13, ARRAY['Brice']::text[]),
  (11, 14, ARRAY['Sidoine']::text[]),
  (11, 15, ARRAY['Albert', 'Arthur', 'Leopold', 'Malo', 'Victoire', 'Victoria']::text[]),
  (11, 16, ARRAY['Margaux', 'Marguerite']::text[]),
  (11, 17, ARRAY['Elisabeth', 'Elise', 'Elsa']::text[]),
  (11, 18, ARRAY['Aude']::text[]),
  (11, 19, ARRAY['Tanguy']::text[]),
  (11, 20, ARRAY['Edmond', 'Octave']::text[]),
  (11, 21, ARRAY['Présentation de Marie']::text[]),
  (11, 22, ARRAY['Cecile']::text[]),
  (11, 23, ARRAY['Clement']::text[]),
  (11, 24, ARRAY['Flore']::text[]),
  (11, 25, ARRAY['Catherine']::text[]),
  (11, 26, ARRAY['Delphine']::text[]),
  (11, 27, ARRAY['Séverin']::text[]),
  (11, 28, ARRAY['Jacques de la Marche']::text[]),
  (11, 29, ARRAY['Saturnin']::text[]),
  (11, 30, ARRAY['Andre', 'Andree']::text[]),
  (12, 1, ARRAY['Florence']::text[]),
  (12, 2, ARRAY['Vivien']::text[]),
  (12, 3, ARRAY['Xavier']::text[]),
  (12, 4, ARRAY['Barbara']::text[]),
  (12, 5, ARRAY['Gérald']::text[]),
  (12, 6, ARRAY['Nicolas', 'Nolan']::text[]),
  (12, 7, ARRAY['Ambre']::text[]),
  (12, 8, ARRAY['Immaculée Conception']::text[]),
  (12, 9, ARRAY['Pierre Fourier']::text[]),
  (12, 10, ARRAY['Romaric']::text[]),
  (12, 11, ARRAY['Daniel', 'Danielle']::text[]),
  (12, 12, ARRAY['Corentin']::text[]),
  (12, 13, ARRAY['Lucie']::text[]),
  (12, 14, ARRAY['Odile']::text[]),
  (12, 15, ARRAY['Christiane']::text[]),
  (12, 16, ARRAY['Alice']::text[]),
  (12, 17, ARRAY['Gaëlle']::text[]),
  (12, 18, ARRAY['Gatien']::text[]),
  (12, 19, ARRAY['Urbain']::text[]),
  (12, 20, ARRAY['Théophile']::text[]),
  (12, 21, ARRAY['Pierre Canisius']::text[]),
  (12, 22, ARRAY['Françoise-Xavière']::text[]),
  (12, 23, ARRAY['Armand']::text[]),
  (12, 24, ARRAY['Adele']::text[]),
  (12, 25, ARRAY['Emmanuel', 'Noel']::text[]),
  (12, 26, ARRAY['Etienne', 'Fanny', 'Stephane', 'Stephanie']::text[]),
  (12, 27, ARRAY['Jean']::text[]),
  (12, 28, ARRAY['Gaspard']::text[]),
  (12, 29, ARRAY['David']::text[]),
  (12, 30, ARRAY['Roger']::text[]),
  (12, 31, ARRAY['Sylvestre']::text[]);
