-- ============================================================
-- Journée mondiale du jour — Popup conditionnel par profil
-- À exécuter dans Supabase > SQL Editor
-- ============================================================

-- 1. Ajouter la colonne show_world_day_popup dans profiles
--    Géré par l'admin de la BDD directement (oui/non)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS show_world_day_popup BOOLEAN NOT NULL DEFAULT false;

-- 2. Créer la table world_days (dataset statique issu de journee-mondiale.com)
CREATE TABLE IF NOT EXISTS public.world_days (
  id          SERIAL PRIMARY KEY,
  month       SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  day         SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
  label       TEXT NOT NULL
);

-- Index pour accélérer la recherche du jour courant
CREATE INDEX IF NOT EXISTS idx_world_days_month_day ON public.world_days (month, day);

-- 3. RLS : tout utilisateur authentifié peut lire world_days
ALTER TABLE public.world_days ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read world_days" ON public.world_days;
CREATE POLICY "Authenticated users can read world_days"
  ON public.world_days FOR SELECT
  TO authenticated
  USING (true);

-- Seuls les admins peuvent modifier world_days
DROP POLICY IF EXISTS "Admins can manage world_days" ON public.world_days;
CREATE POLICY "Admins can manage world_days"
  ON public.world_days FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()));

-- 4. RPC : retourne la/les journée(s) mondiale(s) du jour
--    (utilisée côté client pour éviter d'exposer toute la table)
CREATE OR REPLACE FUNCTION public.get_todays_world_days()
RETURNS TABLE (label TEXT) AS $$
BEGIN
  RETURN QUERY
  SELECT wd.label
  FROM public.world_days wd
  WHERE wd.month = EXTRACT(MONTH FROM CURRENT_DATE)::SMALLINT
    AND wd.day   = EXTRACT(DAY   FROM CURRENT_DATE)::SMALLINT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.get_todays_world_days() TO authenticated;

-- 5. RPC : vérifie si l'utilisateur connecté doit voir le popup
CREATE OR REPLACE FUNCTION public.should_show_world_day_popup()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND show_world_day_popup = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

GRANT EXECUTE ON FUNCTION public.should_show_world_day_popup() TO authenticated;

-- ============================================================
-- 6. Insertion des journées mondiales (source : journee-mondiale.com)
-- ============================================================
-- On vide d'abord pour éviter les doublons en cas de ré-exécution
TRUNCATE public.world_days RESTART IDENTITY;

INSERT INTO public.world_days (month, day, label) VALUES
-- JANVIER
(1,  1,  'Journée du domaine public'),
(1,  1,  'Journée Mondiale de la Paix'),
(1,  2,  'Journée mondiale de la Science-fiction'),
(1,  4,  'Journée mondiale du braille'),
(1,  6,  'Journée Mondiale des orphelins de guerre'),
(1,  7,  'La journée de la quenouille'),
(1,  8,  'Journée internationale du bain moussant'),
(1,  9,  'Journée mondiale de la Corse'),
(1, 10,  'Journée mondiale Tintin'),
(1, 10,  'Journée mondiale de la langue hindi'),
(1, 11,  'Journée mondiale "merci"'),
(1, 13,  'Journée mondiale sans pantalon'),
(1, 14,  'Journée mondiale de la logique'),
(1, 17,  'Journée Internationale de la cuisine italienne'),
(1, 19,  'Journée internationale du Pop Corn'),
(1, 21,  'Journée internationale des câlins'),
(1, 22,  'Journée franco-allemande'),
(1, 23,  'Journée mondiale de l''écriture manuscrite'),
(1, 23,  'Journée mondiale des solitudes'),
(1, 24,  'Journée Internationale de l''éducation'),
(1, 24,  'Journée Internationale du sport féminin'),
(1, 24,  'Journée mondiale de la culture africaine et afro-descendante'),
(1, 26,  'Journée Mondiale de la Douane et sur l''éthique'),
(1, 27,  'Journée de la mémoire de l''Holocauste'),
(1, 28,  'Journée mondiale de la protection des données'),
(1, 29,  'Journée mondiale du caviardage'),
(1, 29,  'Journée Mondiale des lépreux'),
-- FÉVRIER
(2,  2,  'Journée de la marmotte'),
(2,  2,  'Journée Mondiale des Zones Humides'),
(2,  3,  'Journée internationale sans paille'),
(2,  4,  'Journée Mondiale contre le cancer'),
(2,  4,  'Journée internationale de la fraternité humaine'),
(2,  5,  'Journée mondiale du Nutella'),
(2,  6,  'Journée internationale contre les mutilations génitales féminines'),
(2,  7,  'Journée mondiale pour un internet plus sûr'),
(2,  9,  'Journée Mondiale de la Langue Grecque'),
(2, 10,  'Journée internationale des légumineuses'),
(2, 10,  'Journée internationale de l''épilepsie'),
(2, 11,  'Journée européenne du 112'),
(2, 11,  'Journée internationale des femmes et des filles de science'),
(2, 11,  'Journée mondiale des malades'),
(2, 12,  'Journée Internationale des enfants soldats'),
(2, 12,  'Journée internationale Darwin'),
(2, 13,  'Journée mondiale de la radio'),
(2, 15,  'Journée internationale du cancer de l''enfant'),
(2, 18,  'Journée mondiale du pangolin'),
(2, 19,  'Journée internationale de la baleine'),
(2, 20,  'Journée mondiale de la justice sociale'),
(2, 21,  'Journée Internationale de la langue maternelle'),
(2, 22,  'Journée Mondiale du Scoutisme'),
(2, 27,  'Journée mondiale des ONG'),
(2, 27,  'Journée internationale de l''ours polaire'),
(2, 28,  'Journée internationale des maladies rares'),
(2, 28,  'Journée mondiale sans Facebook'),
-- MARS
(3,  1,  'Journée mondiale du compliment'),
(3,  1,  'Journée mondiale de la protection civile'),
(3,  3,  'Journée mondiale de la vie sauvage'),
(3,  4,  'Journée mondiale du tennis'),
(3,  4,  'Journée mondiale de l''obésité'),
(3,  7,  'Journée mondiale contre l''endométriose'),
(3,  8,  'Journée internationale des femmes'),
(3,  9,  'Journée Mondiale du rein'),
(3, 10,  'La journée mondiale du pyjama'),
(3, 11,  'Journée mondiale de la plomberie'),
(3, 12,  'Journée mondiale contre la censure sur internet'),
(3, 14,  'Journée mondiale du Pi et Journée internationale des mathématiques'),
(3, 15,  'Journée mondiale du travail social'),
(3, 15,  'Journée Internationale des droits des consommateurs'),
(3, 18,  'Journée mondiale de la Schizophrénie'),
(3, 18,  'Journée mondiale du recyclage'),
(3, 20,  'Journée internationale sans viande'),
(3, 20,  'Journée Mondiale du Conte'),
(3, 20,  'Journée Internationale de la francophonie'),
(3, 20,  'Journée mondiale du moineau'),
(3, 20,  'Journée mondiale du bonheur'),
(3, 20,  'Journée internationale du macaron'),
(3, 20,  'Journée Mondiale de la santé bucco-dentaire'),
(3, 21,  'Journée Mondiale de la Poésie'),
(3, 21,  'Journée mondiale de la marionnette'),
(3, 21,  'Journée Internationale pour l''élimination de la discrimination raciale'),
(3, 21,  'Journée Internationale des forêts'),
(3, 21,  'Journée Mondiale de la Trisomie 21'),
(3, 22,  'Journée Mondiale de l''eau'),
(3, 23,  'Journée Mondiale de la Météorologie'),
(3, 24,  'Journée Mondiale de lutte contre la tuberculose'),
(3, 25,  'Journée Européenne de l''enfant à naître'),
(3, 25,  'Journée de la procrastination'),
(3, 27,  'Journée Mondiale du théâtre'),
(3, 29,  'Journée internationale des nuages'),
(3, 30,  'Journée Mondiale des troubles bipolaires'),
(3, 31,  'Journée mondiale du Big Bang'),
(3, 31,  'Journée mondiale de la sauvegarde des données informatiques'),
(3, 31,  'Journée Internationale de la Visibilité Trans'),
-- AVRIL
(4,  1,  'Journée internationale de la blague'),
(4,  2,  'Journée mondiale de batailles d''oreillers'),
(4,  2,  'Journée mondiale de sensibilisation à l''autisme'),
(4,  4,  'Journée mondiale du travail invisible'),
(4,  7,  'Journée Mondiale de la santé'),
(4,  8,  'Journée internationale des Roms'),
(4,  9,  'Journée mondiale de la licorne'),
(4, 10,  'Journée internationale des frères et sœurs'),
(4, 11,  'Journée Mondiale de la maladie de Parkinson'),
(4, 12,  'Journée internationale du vol spatial habité'),
(4, 13,  'Journée mondiale du scrabble'),
(4, 15,  'Journée Mondiale de l''Art'),
(4, 15,  'Journée Mondiale du cirque'),
(4, 16,  'Journée mondiale de la voix'),
(4, 17,  'Journée Mondiale de l''hémophilie'),
(4, 17,  'Journée Mondiale des luttes paysannes'),
(4, 18,  'Journée internationale des monuments et des sites'),
(4, 21,  'Journée mondiale de la créativité et de l''innovation'),
(4, 22,  'Journée Mondiale de la Terre'),
(4, 23,  'Journée Mondiale du livre et du droit d''auteur'),
(4, 24,  'Journée mondiale de la lutte contre les méningites'),
(4, 25,  'Journée Mondiale du paludisme'),
(4, 25,  'Journée Mondiale des Manchots'),
(4, 26,  'Journée Mondiale de la propriété intellectuelle'),
(4, 28,  'Journée Mondiale sur la sécurité et la santé au travail'),
(4, 29,  'Journée Internationale de la danse'),
(4, 30,  'Journée Internationale du Jazz'),
(4, 30,  'Journée Mondiale des Mobilités et de l''Accessibilité'),
-- MAI
(5,  1,  'Journée mondiale du travail'),
(5,  2,  'Journée mondiale du thon'),
(5,  3,  'Journée Mondiale de la liberté de la presse'),
(5,  4,  'Journée internationale des pompiers'),
(5,  5,  'Journée mondiale de la langue portugaise'),
(5,  5,  'Journée Mondiale de la Sage-Femme'),
(5,  5,  'Journée mondiale de l''hygiène des mains'),
(5,  6,  'Journée internationale sans régime'),
(5,  7,  'Journée Mondiale du rire'),
(5,  8,  'Journée Mondiale de La Croix Rouge'),
(5,  9,  'Journée de l''Europe'),
(5, 10,  'Journée mondiale du lupus'),
(5, 11,  'Journée mondiale des espèces menacées'),
(5, 12,  'Journée Mondiale de la fibromyalgie'),
(5, 12,  'Journée Internationale de l''infirmière'),
(5, 15,  'Journée Internationale des familles'),
(5, 16,  'Journée internationale du vivre ensemble'),
(5, 16,  'Journée internationale de la lumière'),
(5, 16,  'Journée mondiale de la maladie cœliaque'),
(5, 17,  'Journée internationale contre l''homophobie'),
(5, 17,  'Journée Mondiale des Télécommunications'),
(5, 17,  'Journée Mondiale contre l''hypertension'),
(5, 18,  'Journée Internationale des musées'),
(5, 20,  'Journée mondiale de la métrologie'),
(5, 20,  'Journée mondiale des abeilles'),
(5, 21,  'Journée internationale du thé'),
(5, 21,  'Journée Mondiale de la diversité culturelle pour le dialogue et le développement'),
(5, 22,  'Journée Mondiale de la biodiversité'),
(5, 23,  'Journée mondiale de la tortue'),
(5, 24,  'Journée mondiale du bricolage'),
(5, 25,  'Journée mondiale de la serviette'),
(5, 25,  'Journée mondiale de la thyroïde'),
(5, 25,  'Journée Mondiale de l''Afrique'),
(5, 25,  'Journée Mondiale des enfants disparus'),
(5, 28,  'Journée mondiale de l''hygiène menstruelle'),
(5, 29,  'Journée Internationale des casques bleus'),
(5, 30,  'Journée mondiale de la sclérose en plaques'),
(5, 31,  'Journée mondiale de la loutre'),
(5, 31,  'Journée Mondiale sans tabac'),
-- JUIN
(6,  1,  'Journée mondiale des parents'),
(6,  1,  'Journée mondiale du lait'),
(6,  3,  'Journée mondiale pour le vélo'),
(6,  4,  'Journée Internationale des enfants victimes innocentes d''agression'),
(6,  4,  'Journée mondiale du naturisme'),
(6,  5,  'Journée Mondiale de l''environnement'),
(6,  7,  'Journée mondiale anti contrefaçon'),
(6,  8,  'Journée Mondiale des océans'),
(6, 12,  'Journée Mondiale contre le travail des enfants'),
(6, 13,  'Journée internationale de sensibilisation à l''albinisme'),
(6, 14,  'Journée Mondiale des donneurs de sang'),
(6, 15,  'Journée mondiale contre la faim'),
(6, 15,  'Journée mondiale de lutte contre la maltraitance des personnes âgées'),
(6, 17,  'Journée Mondiale de lutte contre la désertification et la sécheresse'),
(6, 17,  'Journée internationale du surf'),
(6, 19,  'Journée Mondiale de la drépanocytose'),
(6, 20,  'Journée Mondiale des réfugiés'),
(6, 21,  'Journée Mondiale du yoga'),
(6, 21,  'Journée Mondiale de la Sclérose Latérale Amyotrophique'),
(6, 21,  'Journée internationale de la lenteur'),
(6, 21,  'Journée internationale de la girafe'),
(6, 23,  'Journée mondiale pour la fonction publique'),
(6, 23,  'Journée mondiale des veuves'),
(6, 25,  'Journée mondiale des gens de mer'),
(6, 25,  'Journée mondiale du vitiligo'),
(6, 26,  'Journée Internationale contre l''abus et le trafic illicite de drogues'),
(6, 26,  'Journée Internationale des Nations Unies pour le soutien aux victimes de la torture'),
(6, 27,  'Journée Mondiale contre l''abandon des animaux de compagnie'),
(6, 30,  'Journée mondiale des astéroïdes'),
-- JUILLET
(7,  1,  'Journée mondiale du reggae'),
(7,  2,  'Journée mondiale des OVNI'),
(7,  3,  'Journée mondiale sans sacs plastique'),
(7,  6,  'Journée Internationale du baiser'),
(7,  7,  'Journée mondiale de la langue Kiswahili'),
(7, 11,  'Journée Mondiale de la population'),
(7, 14,  'Journée Mondiale de l''Orque'),
(7, 15,  'Journée mondiale des compétences des jeunes'),
(7, 16,  'Journée mondiale des serpents'),
(7, 17,  'Journée mondiale de la justice internationale'),
(7, 17,  'Journée mondiale des émojis'),
(7, 18,  'Journée internationale Nelson Mandela'),
(7, 20,  'Journée mondiale du jeu d''échecs'),
(7, 23,  'Journée mondiale des grands-parents et des personnes âgées'),
(7, 23,  'Journée mondiale des dauphins'),
(7, 25,  'Journée mondiale de prévention de la noyade'),
(7, 28,  'Journée mondiale contre l''hépatite'),
(7, 29,  'Journée internationale du tigre'),
(7, 30,  'Journée internationale de l''amitié'),
(7, 31,  'Journée internationale de la femme africaine'),
-- AOÛT
(8,  4,  'Journée mondiale de la bière'),
(8,  8,  'Journée internationale du chat'),
(8,  9,  'Journée Internationale des Populations autochtones'),
(8, 10,  'Journée mondiale du lion'),
(8, 12,  'Journée Internationale de la jeunesse'),
(8, 12,  'Journée mondiale des éléphants'),
(8, 13,  'Journée internationale des gauchers'),
(8, 16,  'Journée mondiale du cerf-volant'),
(8, 17,  'Journée internationale du chat noir'),
(8, 19,  'Journée mondiale de la photographie'),
(8, 19,  'Journée mondiale de l''aide humanitaire'),
(8, 20,  'Journée mondiale du moustique'),
(8, 21,  'Journée Internationale du souvenir en hommage aux victimes du terrorisme'),
(8, 23,  'Journée Internationale du souvenir de la traite negrière et de son abolition'),
(8, 26,  'Journée mondiale du chien'),
(8, 29,  'Journée Internationale contre les essais nucléaires'),
(8, 30,  'Journée Internationale des personnes disparues'),
(8, 31,  'Journée mondiale du blog'),
(8, 31,  'Journée internationale de prévention des overdoses'),
-- SEPTEMBRE
(9,  3,  'Journée mondiale des gratte-ciel'),
(9,  4,  'Journée mondiale de la santé sexuelle'),
(9,  5,  'Journée internationale de la charité'),
(9,  7,  'Journée mondiale des lymphomes'),
(9,  8,  'Journée mondiale de la physiothérapie'),
(9,  8,  'Journée Internationale de l''alphabétisation'),
(9,  9,  'Journée mondiale des premiers secours'),
(9, 10,  'Journée Mondiale de prévention du suicide'),
(9, 11,  'Journée mondiale de lutte contre le terrorisme'),
(9, 13,  'Journée Mondiale contre la Septicémie'),
(9, 13,  'Journée Mondiale des programmeurs et développeurs'),
(9, 15,  'Journée internationale de la démocratie'),
(9, 16,  'Journée mondiale du logiciel libre'),
(9, 16,  'Journée Internationale de la protection de la couche d''ozone'),
(9, 16,  'Journée mondiale du nettoyage'),
(9, 17,  'Journée Mondiale sans voiture'),
(9, 17,  'Journée mondiale pour le don de moelle osseuse'),
(9, 18,  'Journée internationale du bambou'),
(9, 19,  'Journée Internationale du Parler Pirate'),
(9, 21,  'Journée Internationale de la paix'),
(9, 21,  'Journée Mondiale de la maladie d''Alzheimer'),
(9, 22,  'Journée mondiale du rhinocéros'),
(9, 23,  'Journée de la bisexualité'),
(9, 23,  'Journée internationale des langues des signes'),
(9, 25,  'Journée mondiale du rêve'),
(9, 25,  'Journée mondiale des pharmaciens'),
(9, 26,  'Journée mondiale de la contraception'),
(9, 26,  'Journée Européenne des langues'),
(9, 27,  'Journée mondiale du tourisme'),
(9, 28,  'Journée mondiale contre la rage'),
(9, 29,  'Journée Mondiale du coeur'),
(9, 30,  'Journée mondiale de la traduction'),
(9, 30,  'Journée Mondiale des sourds'),
-- OCTOBRE
(10,  1,  'Journée mondiale du végétarisme'),
(10,  1,  'Journée internationale du café'),
(10,  1,  'Journée Mondiale du chocolat'),
(10,  1,  'Journée Internationale des personnes âgées'),
(10,  2,  'Journée Internationale de la non violence'),
(10,  2,  'Journée mondiale de l''architecture'),
(10,  4,  'Journée Mondiale des animaux'),
(10,  5,  'Journée Mondiale des enseignantes et des enseignants'),
(10,  6,  'Journée mondiale du sourire'),
(10,  6,  'Journée mondiale de la paralysie cérébrale'),
(10,  6,  'Journée nationale des aidants'),
(10,  8,  'Journée internationale du poulpe'),
(10,  9,  'Journée Mondiale de La Poste'),
(10, 10,  'Journée Mondiale contre la peine de mort'),
(10, 10,  'Journée Mondiale de la santé mentale'),
(10, 11,  'Journée Internationale des Filles'),
(10, 11,  'Journée Internationale du coming out'),
(10, 12,  'Journée mondiale de l''arthrite'),
(10, 12,  'Journée mondiale pour la vue'),
(10, 13,  'Journée mondiale de la thrombose'),
(10, 13,  'Journée mondiale de l''oeuf'),
(10, 13,  'Journée Internationale de la prévention des catastrophes naturelles'),
(10, 15,  'Journée mondiale de sensibilisation au deuil périnatal'),
(10, 15,  'Journée Internationale de la Canne Blanche'),
(10, 15,  'Journée Mondiale du lavage des mains'),
(10, 16,  'Journée mondiale du pain'),
(10, 16,  'Journée mondiale contre la douleur'),
(10, 16,  'Journée Mondiale de l''alimentation'),
(10, 17,  'Journée mondiale du don d''organes et de la greffe'),
(10, 17,  'Journée Mondiale du refus de la misère'),
(10, 18,  'Journée Mondiale de la ménopause'),
(10, 19,  'Journée mondiale contre le cancer du sein'),
(10, 20,  'Journée mondiale de la statistique'),
(10, 20,  'Journée Mondiale de l''ostéoporose'),
(10, 21,  'Journée mondiale des vers de terre'),
(10, 22,  'Journée Mondiale du bégaiement'),
(10, 22,  'Journée mondiale de l''énergie'),
(10, 24,  'Journée des Nations Unies'),
(10, 24,  'Journée mondiale de lutte contre la polio'),
(10, 25,  'Journée internationale du nanisme'),
(10, 25,  'Journée Mondiale des pâtes'),
(10, 27,  'Journée mondiale du patrimoine audiovisuel'),
(10, 27,  'Journée mondiale de l''ergothérapie'),
(10, 28,  'Journée mondiale du judo'),
(10, 28,  'Journée mondiale du cinéma d''animation'),
(10, 29,  'Journée mondiale des accidents vasculaires cérébraux'),
(10, 29,  'Journée Mondiale du psoriasis'),
(10, 30,  'Journée mondiale de la Vie'),
(10, 31,  'Journée mondiale des villes'),
(10, 31,  'Journée mondiale de l''épargne'),
-- NOVEMBRE
(11,  1,  'Journée Mondiale Végane'),
(11,  3,  'Journée Mondiale de la gentillesse'),
(11,  4,  'Journée du bon sens'),
(11,  6,  'Journée Internationale pour la préservation de l''environnement en temps de guerre'),
(11,  6,  'Journée Mondiale sans papier'),
(11,  8,  'Journée internationale de la radiologie'),
(11, 10,  'Journée mondiale de l''utilisabilité'),
(11, 10,  'Journée Mondiale de la science au service de la paix et du développement'),
(11, 10,  'Journée internationale des stagiaires'),
(11, 10,  'Journée nationale de lutte contre le harcèlement scolaire'),
(11, 11,  'Journée internationale des célibataires'),
(11, 11,  'Journée mondiale de la qualité'),
(11, 12,  'Journée Mondiale de la pneumonie'),
(11, 13,  'Journée mondiale des pauvres'),
(11, 14,  'Journée mondiale du diabète'),
(11, 15,  'Journée mondiale des écrivains en prison'),
(11, 16,  'Journée Internationale de la tolérance'),
(11, 17,  'Journée Mondiale de la Prématurité'),
(11, 17,  'Journée de la Philosophie à l''UNESCO'),
(11, 18,  'Journée européenne d''information sur les antibiotiques'),
(11, 18,  'Journée mondiale du jeu vidéo'),
(11, 19,  'Journée mondiale pour la prévention des abus envers les enfants'),
(11, 19,  'Journée Mondiale des toilettes'),
(11, 19,  'Journée internationale de l''homme'),
(11, 20,  'Journée Internationale des droits de l''enfant'),
(11, 20,  'Journée mondiale du souvenir des victimes des accidents de la route'),
(11, 21,  'Journée Mondiale de la Télévision'),
(11, 24,  'Journée internationale des professeurs de français'),
(11, 25,  'Journée Internationale pour l''élimination de la violence à l''égard des femmes'),
(11, 26,  'Journée Mondiale Sans Achats'),
(11, 29,  'Journée mondiale de la générosité'),
(11, 30,  'Journée mondiale des Villes pour la Vie'),
-- DÉCEMBRE
(12,  1,  'Journée Mondiale de la lutte contre le SIDA'),
(12,  2,  'Journée Internationale pour l''abolition de l''esclavage'),
(12,  3,  'Journée Internationale des personnes handicapées'),
(12,  5,  'Journée Internationale du Ninja'),
(12,  5,  'Journée mondiale des sols'),
(12,  5,  'Journée mondiale du bénévolat'),
(12,  7,  'Journée Internationale de l''aviation civile'),
(12,  8,  'Journée Mondiale du Climat'),
(12,  9,  'Journée nationale de la laïcité'),
(12,  9,  'Journée Mondiale des Nations Unies contre la corruption'),
(12, 10,  'Journée internationale pour les droits des animaux'),
(12, 10,  'Journée Mondiale des droits de l''Homme'),
(12, 11,  'Journée Internationale de la montagne'),
(12, 11,  'Journée mondiale du chant choral'),
(12, 13,  'Journée internationale de la raclette'),
(12, 15,  'Journée internationale du pull de Noël'),
(12, 18,  'Journée internationale des migrants'),
(12, 18,  'Journée mondiale pour la langue Arabe'),
(12, 20,  'Journée internationale de la solidarité humaine'),
(12, 21,  'Journée Mondiale de l''Orgasme'),
(12, 27,  'Journée internationale de la préparation aux épidémies');
