import {
  ACADEMY_DIFFUSION_HREF,
  ACADEMY_LINKS,
  GUIDES_FAQ_HREF,
  GUIDES_LEXIQUE_HREF,
  GUIDES_MEDIA_HREF,
  GUIDES_STUDIO_HREF,
  GUIDES_TUTOS_HREF,
  IA_HREF,
  MON_ESPACE_MES_PROJETS_HREF,
  STRATEGIE_CARTOGRAPHIE_HREF,
  STRATEGIE_PLAN_MEDIA_HREF,
  STRATEGIE_RETROPLANNING_HREF,
  VENTE2_SMS_HREF,
  VENTE2_SOCIAL_HREF,
  VENTE2_STUDIO_TARIFS_HREF,
} from '@/lib/nav-config'
import { SITE_DOCUMENT_SECTIONS } from '@/lib/site-documents'

type CatalogEntry = {
  id: string
  title: string
  description?: string
  href: string
  category: string
  keywords?: string[]
  adminOnly?: boolean
  hiddenForClient?: boolean
}

function entry(
  partial: CatalogEntry,
): CatalogEntry {
  return partial
}

/** Rubriques et sous-rubriques indexées pour la recherche globale. */
export const SITE_SEARCH_CATALOG: CatalogEntry[] = [
  entry({
    id: 'home',
    title: 'Accueil',
    href: '/home',
    category: 'Général',
    keywords: ['home', 'accueil', 'dashboard'],
  }),
  entry({
    id: 'diffusion',
    title: 'Diffusion',
    description: 'Modules de formation commerciale Link Academy',
    href: ACADEMY_DIFFUSION_HREF,
    category: 'Academy',
    keywords: ['formation', 'modules', 'apprentissage'],
  }),
  entry({
    id: 'cartographie',
    title: 'Cartographie',
    description: 'Carte des zones de diffusion et estimation de population',
    href: STRATEGIE_CARTOGRAPHIE_HREF,
    category: 'Stratégie',
    keywords: ['zone', 'zones', 'carte', 'géographie', 'ville', 'rayon', 'département', 'région', 'codes postaux', 'population', 'ciblage géographique'],
  }),
  entry({
    id: 'cartographie-zones',
    title: 'Zones de diffusion',
    description: 'Composez des zones : ville et rayon, département, région, codes postaux',
    href: STRATEGIE_CARTOGRAPHIE_HREF,
    category: 'Stratégie',
    keywords: ['zone', 'zones', 'cartographie', 'carte', 'audience', 'potentiel'],
  }),
  entry({
    id: 'studio',
    title: 'Studio — Guide des formats visuels',
    description: 'Formats, contraintes et recommandations par plateforme publicitaire',
    href: GUIDES_STUDIO_HREF,
    category: 'Guides',
    keywords: ['visuel', 'format', 'créa', 'graphisme', 'bannière', 'vidéo'],
  }),
  entry({
    id: 'studio-meta',
    title: 'Studio — META',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['meta', 'facebook', 'instagram', 'story', 'carrousel', 'reels', 'zone', 'marges'],
  }),
  entry({
    id: 'studio-display',
    title: 'Studio — Display',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['display', 'google', 'programmatique', 'bannière'],
  }),
  entry({
    id: 'studio-search',
    title: 'Studio — Search',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['search', 'google ads', 'sea', 'mots clés', 'annonce search'],
  }),
  entry({
    id: 'studio-linkedin',
    title: 'Studio — LinkedIn',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['linkedin', 'b2b', 'sponsored'],
  }),
  entry({
    id: 'studio-tiktok',
    title: 'Studio — TikTok',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['tiktok', 'vertical', 'in-feed'],
  }),
  entry({
    id: 'studio-snapchat',
    title: 'Studio — Snapchat',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['snapchat', 'snap', 'story'],
  }),
  entry({
    id: 'studio-spotify',
    title: 'Studio — Spotify',
    href: GUIDES_STUDIO_HREF,
    category: 'Studio',
    keywords: ['spotify', 'audio'],
  }),
  entry({
    id: 'media',
    title: 'Média',
    href: GUIDES_MEDIA_HREF,
    category: 'Guides',
    keywords: ['médiathèque', 'bibliothèque', 'assets'],
    adminOnly: true,
  }),
  entry({
    id: 'vente2-social',
    title: 'Mon espace — Social Média',
    href: VENTE2_SOCIAL_HREF,
    category: 'Mon espace',
    keywords: ['calculateur', 'social media', 'meta', 'tiktok', 'linkedin'],
  }),
  entry({
    id: 'vente2-sms',
    title: 'Mon espace — SMS & RCS',
    href: VENTE2_SMS_HREF,
    category: 'Mon espace',
    keywords: ['sms', 'rcs', 'mobile', 'devis'],
  }),
  entry({
    id: 'mon-espace-tarifs-studio',
    title: 'Mon espace — Tarifs studio',
    href: VENTE2_STUDIO_TARIFS_HREF,
    category: 'Mon espace',
    keywords: ['tarif', 'studio', 'créa', 'graphisme', 'devis'],
  }),
  entry({
    id: 'strategie-plan-media',
    title: 'Stratégie — Plan Média',
    description: 'Simulateur média multi-plateformes',
    href: STRATEGIE_PLAN_MEDIA_HREF,
    category: 'Stratégie',
    keywords: ['simulateur', 'impressions', 'pénétration', 'pression', 'kpi'],
    adminOnly: true,
  }),
  entry({
    id: 'strategie-retroplanning',
    title: 'Stratégie — Rétroplanning',
    href: STRATEGIE_RETROPLANNING_HREF,
    category: 'Stratégie',
    keywords: ['rétroplanning', 'gantt', 'planning', 'calendrier', 'dates'],
    adminOnly: true,
  }),
  entry({
    id: 'ia',
    title: 'IA',
    description: 'Analyses et présentations générées par intelligence artificielle',
    href: IA_HREF,
    category: 'Admin',
    keywords: ['intelligence artificielle', 'analyse', 'présentation', 'pdf'],
    adminOnly: true,
  }),
  entry({
    id: 'mon-espace',
    title: 'Mon espace',
    description: 'Stratégies, mockups, simulations et devis enregistrés',
    href: MON_ESPACE_MES_PROJETS_HREF,
    category: 'Admin',
    keywords: ['sauvegarde', 'enregistrement', 'stratégies', 'mockup', 'devis'],
    adminOnly: true,
  }),
  entry({
    id: 'mon-espace-strategy',
    title: 'Mon espace — Calculateur de vente',
    href: MON_ESPACE_MES_PROJETS_HREF,
    category: 'Mon espace',
    keywords: ['stratégie', 'social media', 'sauvegarde'],
    adminOnly: true,
  }),
  entry({
    id: 'mon-espace-mockup',
    title: 'Mon espace — Mockups',
    href: MON_ESPACE_MES_PROJETS_HREF,
    category: 'Mon espace',
    keywords: ['mockup', 'visuel', 'aperçu'],
    adminOnly: true,
  }),
  entry({
    id: 'documents',
    title: 'Documents',
    description: 'Guides, templates PowerPoint et fiches plateformes',
    href: '/documents',
    category: 'Aide',
    keywords: ['guide', 'pdf', 'powerpoint', 'keynote', 'téléchargement'],
    hiddenForClient: true,
  }),
  entry({
    id: 'glossaire',
    title: 'Lexique',
    description: 'Définitions des termes publicitaires et marketing',
    href: GUIDES_LEXIQUE_HREF,
    category: 'Guides',
    keywords: ['définition', 'terme', 'lexique', 'vocabulaire'],
  }),
  entry({
    id: 'faq',
    title: 'FAQ',
    description: 'Questions fréquentes sur les campagnes et le tracking',
    href: GUIDES_FAQ_HREF,
    category: 'Guides',
    keywords: ['question', 'réponse', 'aide'],
  }),
  entry({
    id: 'tutos',
    title: 'Tutos',
    description: 'Vidéos tutorielles Vimeo',
    href: GUIDES_TUTOS_HREF,
    category: 'Guides',
    keywords: ['tutoriel', 'vidéo', 'vimeo', 'pixel', 'gtm', 'ga4'],
    adminOnly: true,
  }),
  entry({
    id: 'calcul-cpm-cpc',
    title: 'Calcul CPM / CPC',
    description: 'Comparez KPIs atteints et objectifs vendus',
    href: '/calcul-cpm-cpc',
    category: 'Aide',
    keywords: ['cpm', 'cpc', 'coût', 'delta', 'kpi', 'calcul'],
    adminOnly: true,
  }),
  entry({
    id: 'mockup',
    title: 'Mockup',
    description: 'Aperçu publicitaire multi-plateformes',
    href: '/mockup',
    category: 'Aide',
    keywords: ['aperçu', 'visuel', 'preview'],
    adminOnly: true,
  }),
  entry({
    id: 'formation-ciblage-geo',
    title: 'Zones géographiques',
    description: 'Pays, régions, villes, codes postaux ou rayon autour d\'un point',
    href: '/academy/ciblage',
    category: 'Formation — Ciblage',
    keywords: ['zone', 'zones', 'géographique', 'ville', 'rayon', 'ciblage', 'local'],
  }),
  entry({
    id: 'formation-architecture-zones',
    title: 'Architecture — zones géographiques',
    description: 'Campagne mono-zone, multi-zones ou une campagne par zone',
    href: '/academy/architecture-campagnes',
    category: 'Formation — Architecture',
    keywords: ['zone', 'zones', 'géographique', 'meta', 'budget', 'répartition'],
  }),
  entry({
    id: 'formation-optimisations-zones',
    title: 'Optimisations — zones et segments',
    description: 'Optimiser visuels, âges, zones, audiences, mots clés, placements',
    href: '/academy/optimisations',
    category: 'Formation — Optimisations',
    keywords: ['zone', 'zones', 'optimisation', 'segment', 'performance'],
  }),
  entry({
    id: 'formation-demandes-potentiels',
    title: 'Demandes de potentiels',
    description: 'Fiche brief pour estimer le potentiel d\'une campagne',
    href: '/academy/demandes-potentiels',
    category: 'Formation',
    keywords: ['potentiel', 'brief', 'monday', 'audience'],
    hiddenForClient: true,
  }),
  entry({
    id: 'formation-tracking',
    title: 'Tracking',
    description: 'Suivi et analyse des performances de campagne',
    href: '/academy/tracking',
    category: 'Formation',
    keywords: ['pixel', 'gtm', 'ga4', 'conversion', 'suivi'],
  }),
  entry({
    id: 'formation-score-qualite',
    title: 'Score qualité',
    href: '/academy/score-qualite',
    category: 'Formation',
    keywords: ['qualité', 'google ads', 'landing page'],
  }),
  entry({
    id: 'chefferie',
    title: 'Chefferie de projet',
    href: '/chefferie',
    category: 'Ressources',
    keywords: ['chef de projet', 'production', 'monday'],
  }),
  ...SITE_DOCUMENT_SECTIONS.flatMap((section) =>
    section.items.map((doc) =>
      entry({
        id: `doc-${doc.id}`,
        title: doc.title,
        description: doc.description,
        href: '/documents',
        category: `Documents — ${section.title}`,
        keywords: [doc.format, section.title, 'télécharger', 'guide'],
        hiddenForClient: true,
      }),
    ),
  ),
]
